
import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const MonaSans = localFont({
  src: [
    {
      path: './assets/fonts/MonaSans/WOFF 2/MonaSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/MonaSans/WOFF 2/MonaSans-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './assets/fonts/MonaSans/WOFF 2/MonaSans-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './assets/fonts/MonaSans/WOFF 2/MonaSans-BoldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={MonaSans.className}>{children}</body>
    </html>
  )
}
